spring:
  application:
    name: ProjetoFiap

  datasource:
    url: jdbc:h2:mem:testedb
    driverClassName: org.h2.Driver
    username: test
    password: test
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

custom:
  sal: salParaTeste

security:
  jwt:
    expiration: 50000
#    esta é uma chave para testes, não é utilizada além do ambiente de testes
    signatureKey: "CoVixxWQ+xzC9tQ5ym90aBfmB+MhTT+4FEw3gPY0oTRo+Ys5wLqEuH/gqFv3R1diRSiwFY9Qw+WL/CAIlsZN0w=="

