spring:
  application:
    name: ProjetoFiap

  datasource:
    url: jdbc:h2:mem:testedb
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

custom:
  sal: salParaTeste

