spring:
  application:
    name: ProjetoFiap

  datasource:
    url: ${DATABASE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

custom:
  sal: ${SAL}

security:
  jwt:
    expiration: 50000
    signatureKey: ${SIGNATURE_KEY}