version: '3.9'

services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=restaurante'
      - 'MYSQL_PASSWORD=teste'
      - 'MYSQL_ROOT_PASSWORD=testeRoot'
      - 'MYSQL_USER=teste'
    ports:
      - '3306:3306'